spring.application.name=review-service
server.port=8086

aws.region=us-east-1
aws.dynamodb.table.reviews=reviews

# OpenFeign Order Service Endpoint (API Gateway or direct internal URL)
orderservice.url=https://73svzbgcrf.execute-api.us-east-1.amazonaws.com
# Snyk trigger

