server.port=8083
spring.application.name=payment-service


aws.dynamodb.region=us-east-1

aws.dynamodb.tableName=Payments
aws.region=us-east-1
cognito.userPoolId=us-east-1_uAT4POYI0
sns.payment-events.topic.arn=arn:aws:sns:us-east-1:943755888207:payment-events
#for tests
gateway.url=http://localhost
# Snyk trigger 8




