server.port=8084
spring.application.name=order-service

aws.dynamodb.region=us-east-1
aws.dynamodb.tableName=Orders
#for tests
gateway.url=http://localhost
internal.secret=mySecretKey-Deva
# Snyk trigger 14

